#%RAML 1.0 ResourceType
get:
  description: <<addDescription>>
  queryParameters: <<queryParams>>
  responses: 
    200:
      body: 
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>