#%RAML 1.0 NamedExample

[
    {
        "STMT_ENTRY_ID": "205620576556572.020001",
        "ACCOUNT_NUMBER": "0210102205002",
        "PROCESSING_DATE": "20240417",
        "BOOKING_DATE": "20240417",
        "VALUE_DATE": "20240410",
        "CURRENCY": "BHD",
        "AMOUNT_FCY": null,
        "AMOUNT_LCY": "4000.000",
        "EXCHANGE_RATE": null,
        "OUR_REFERENCE": null,
        "TRANS_REFERENCE": "DC241082000001030",
        "COMPANY_CODE": "BH0020010",
        "PRODUCT_CATEGORY": "6001",
        "ACCOUNT_OFFICER": "1361"
    },
    {
        "STMT_ENTRY_ID": "208335942258966.100001",
        "ACCOUNT_NUMBER": "0210102205002",
        "PROCESSING_DATE": "20250115",
        "BOOKING_DATE": "20250113",
        "VALUE_DATE": "20250115",
        "CURRENCY": "BHD",
        "AMOUNT_FCY": null,
        "AMOUNT_LCY": "-4013.631",
        "EXCHANGE_RATE": null,
        "OUR_REFERENCE": "SCTRSC25013S7CJJ",
        "TRANS_REFERENCE": "SCTRSC25013S7CJJ",
        "COMPANY_CODE": "BH0020010",
        "PRODUCT_CATEGORY": "6001",
        "ACCOUNT_OFFICER": "1361"
    }
]