name: Deploy Mule App to CloudHub TAA

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

        - name: Deploy to CloudHub
        env:
          C_ID: "${{ secrets.ANYPOINT_CLIENT_ID }}"
          C_SECRET: "${{ secrets.ANYPOINT_CLIENT_SECRET }}"
        run: |
          mvn clean deploy -DmuleDeploy \
          -Danypoint.client.id=$C_ID \
          -Danypoint.client.secret=$C_SECRET \
          "-Dserver.anypoint-exchange-v3.username=~~~Client~~~" \
          "-Dserver.anypoint-exchange-v3.password=$C_ID~?~$C_SECRET"